import 'package:cloud_firestore/cloud_firestore.dart';

class FirestoreSeed {
  static Future<void> seedPois() async {
    final col = FirebaseFirestore.instance.collection('pois');
    final snapshot = await col.limit(1).get();
    if (snapshot.docs.isNotEmpty) return; // already seeded

    final pois = [
      {
        'id': 'kata_beach',
        'name': 'Kata Beach',
        'location': 'Kata, Phuket',
        'category': 'Beach',
        'rating': 4.7,
        'description': 'A beautiful beach popular for swimming, sunsets, and a relaxed atmosphere.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '2 - 4 hours',
        'priceRange': 'Free',
        'imagePath': 'assets/images/kata_beach.jpg',
        'tags': ['Beach', 'Nature'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'patong_beach',
        'name': 'Patong Beach',
        'location': 'Patong, Phuket',
        'category': 'Beach',
        'rating': 4.5,
        'description': 'A lively beach area known for nightlife, shopping, and entertainment.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '2 - 4 hours',
        'priceRange': 'Free',
        'imagePath': 'assets/images/patong_beach.jpg',
        'tags': ['Popular', 'Nightlife'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'freedom_beach',
        'name': 'Freedom Beach',
        'location': 'Patong, Phuket',
        'category': 'Beach',
        'rating': 4.8,
        'description': 'A quieter hidden beach with soft sand and clear water, great for relaxing.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '2 - 3 hours',
        'priceRange': 'Free',
        'imagePath': 'assets/images/freedom_beach.jpg',
        'tags': ['Hidden Gem', 'Nature'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'surin_beach',
        'name': 'Surin Beach',
        'location': 'Surin, Phuket',
        'category': 'Beach',
        'rating': 4.6,
        'description': 'Upscale beach area loved for clear water, sunbeds, and trendy beach clubs.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '2 - 3 hours',
        'priceRange': '฿',
        'imagePath': 'assets/images/surin_beach.jpg',
        'tags': ['Beach', 'Upscale'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'nai_harn_beach',
        'name': 'Nai Harn Beach',
        'location': 'Nai Harn, Phuket',
        'category': 'Beach',
        'rating': 4.8,
        'description': 'A scenic and peaceful beach tucked in the south, surrounded by hills.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '2 - 3 hours',
        'priceRange': 'Free',
        'imagePath': 'assets/images/nai_harn_beach.jpg',
        'tags': ['Peaceful', 'Scenic'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'the_big_buddha',
        'name': 'The Big Buddha',
        'location': 'Karon, Phuket',
        'category': 'Temple',
        'rating': 4.8,
        'description': 'A famous landmark with panoramic views and a peaceful hilltop atmosphere.',
        'longDescription': '',
        'openHours': '8:00 AM - 7:30 PM',
        'estimatedTime': '1 - 2 hours',
        'priceRange': 'Free',
        'imagePath': 'assets/images/the_big_buddha.jpg',
        'tags': ['Must See', 'Culture'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'wat_chalong',
        'name': 'Wat Chalong',
        'location': 'Chalong, Phuket',
        'category': 'Temple',
        'rating': 4.8,
        'description': 'A significant Buddhist temple complex with ornate architecture and spiritual importance.',
        'longDescription': '',
        'openHours': '7:00 AM - 5:00 PM',
        'estimatedTime': '1 hour',
        'priceRange': 'Free',
        'imagePath': 'assets/images/wat_chalong.jpg',
        'tags': ['Temple', 'Culture'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'phuket_elephant_sanctuary',
        'name': 'Phuket Elephant Sanctuary',
        'location': 'Paklok, Phuket',
        'category': 'Nature',
        'rating': 4.9,
        'description': 'An ethical elephant sanctuary where visitors can observe rescued elephants.',
        'longDescription': '',
        'openHours': '9:00 AM - 5:00 PM',
        'estimatedTime': '2 - 3 hours',
        'priceRange': '฿฿฿',
        'imagePath': 'assets/images/phuket_elephant_sanctuary.jpg',
        'tags': ['Nature', 'Ethical'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'sirinat_national_park',
        'name': 'Sirinat National Park',
        'location': 'North Phuket',
        'category': 'Nature',
        'rating': 4.6,
        'description': 'A peaceful natural area with beaches, forest, and wildlife observation.',
        'longDescription': '',
        'openHours': '8:00 AM - 6:00 PM',
        'estimatedTime': '2 - 4 hours',
        'priceRange': '฿',
        'imagePath': 'assets/images/sirinat_national_park.jpg',
        'tags': ['Nature', 'Relax'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'koh_sirey',
        'name': 'Koh Sirey',
        'location': 'East Phuket',
        'category': 'Nature',
        'rating': 4.3,
        'description': 'A small island connected by bridge, known for mangrove forests and sea views.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '1 - 2 hours',
        'priceRange': 'Free',
        'imagePath': 'assets/images/koh_sirey.jpg',
        'tags': ['Nature', 'Mangrove'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'old_phuket_town',
        'name': 'Old Phuket Town',
        'location': 'Phuket City',
        'category': 'Culture',
        'rating': 4.9,
        'description': 'Historic streets, colorful Sino-Portuguese buildings, cafes, and local food.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '2 - 3 hours',
        'priceRange': 'Free',
        'imagePath': 'assets/images/old_phuket_town.jpg',
        'tags': ['Heritage', 'Food'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'phuket_fantasea',
        'name': 'Phuket Fantasea',
        'location': 'Kamala, Phuket',
        'category': 'Culture',
        'rating': 4.5,
        'description': 'A spectacular cultural theme park with Thai shows, acrobatics, and elephants.',
        'longDescription': '',
        'openHours': '5:30 PM - 11:30 PM',
        'estimatedTime': '3 - 4 hours',
        'priceRange': '฿฿฿',
        'imagePath': 'assets/images/phuket_fantasea.jpg',
        'tags': ['Show', 'Culture'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'rawai_seafood_market',
        'name': 'Rawai Seafood Market',
        'location': 'Rawai, Phuket',
        'category': 'Food',
        'rating': 4.6,
        'description': 'Buy fresh seafood by weight directly from fishermen and have it cooked on the spot.',
        'longDescription': '',
        'openHours': '9:00 AM - 9:00 PM',
        'estimatedTime': '1 - 2 hours',
        'priceRange': '฿฿',
        'imagePath': 'assets/images/rawai_seafood_market.jpg',
        'tags': ['Seafood', 'Local'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'phuket_town_walking_street',
        'name': 'Phuket Town Walking Street',
        'location': 'Phuket City',
        'category': 'Food',
        'rating': 4.7,
        'description': 'A vibrant Sunday night market packed with local food stalls and street art.',
        'longDescription': '',
        'openHours': 'Sun 4:00 PM - 10:00 PM',
        'estimatedTime': '1 - 2 hours',
        'priceRange': '฿',
        'imagePath': 'assets/images/phuket_town_walking_street.jpg',
        'tags': ['Street Food', 'Market'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'blue_elephant_restaurant',
        'name': 'Blue Elephant Restaurant',
        'location': 'Old Town, Phuket',
        'category': 'Food',
        'rating': 4.7,
        'description': 'Award-winning Thai cuisine in a beautiful colonial mansion with cooking classes.',
        'longDescription': '',
        'openHours': '11:30 AM - 10:00 PM',
        'estimatedTime': '1.5 - 2 hours',
        'priceRange': '฿฿฿',
        'imagePath': 'assets/images/blue_elephant_restaurant.jpg',
        'tags': ['Fine Dining', 'Thai'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'tiger_kingdom',
        'name': 'Tiger Kingdom',
        'location': 'Kathu, Phuket',
        'category': 'Adventure',
        'rating': 4.2,
        'description': 'Get up close with tigers of all ages in a supervised and safe environment.',
        'longDescription': '',
        'openHours': '9:00 AM - 6:00 PM',
        'estimatedTime': '1 - 2 hours',
        'priceRange': '฿฿฿',
        'imagePath': 'assets/images/tiger_kingdom.jpg',
        'tags': ['Adventure', 'Wildlife'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'atv_and_zipline',
        'name': 'ATV & Zipline Tour',
        'location': 'Kathu, Phuket',
        'category': 'Adventure',
        'rating': 4.5,
        'description': 'Thrilling ATV rides through jungle trails and zipline rides over the canopy.',
        'longDescription': '',
        'openHours': '8:00 AM - 5:00 PM',
        'estimatedTime': '2 - 3 hours',
        'priceRange': '฿฿฿',
        'imagePath': 'assets/images/atv_&_zipline.jpg',
        'tags': ['Thrill', 'Outdoor'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'phi_phi_islands_day_trip',
        'name': 'Phi Phi Islands Day Trip',
        'location': 'Rassada Pier, Phuket',
        'category': 'Adventure',
        'rating': 4.9,
        'description': 'A full-day boat tour to the iconic Phi Phi Islands — snorkeling, Maya Bay, and more.',
        'longDescription': '',
        'openHours': '7:30 AM - 6:00 PM',
        'estimatedTime': 'Full Day',
        'priceRange': '฿฿฿',
        'imagePath': 'assets/images/phi_phi_island.jpg',
        'tags': ['Must Do', 'Snorkel'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'bangla_road',
        'name': 'Bangla Road',
        'location': 'Patong, Phuket',
        'category': 'Nightlife',
        'rating': 4.3,
        'description': 'A famous nightlife street packed with bars, clubs, lights, and late-night energy.',
        'longDescription': '',
        'openHours': '6:00 PM - Late',
        'estimatedTime': '1 - 3 hours',
        'priceRange': '฿฿',
        'imagePath': 'assets/images/bangla_road.jpg',
        'tags': ['Nightlife', 'Popular'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'illuzion_club',
        'name': 'Illuzion Club',
        'location': 'Patong, Phuket',
        'category': 'Nightlife',
        'rating': 4.4,
        'description': "One of Phuket's biggest and most popular clubs with top DJs and light shows.",
        'longDescription': '',
        'openHours': '9:00 PM - Late',
        'estimatedTime': '2 - 4 hours',
        'priceRange': '฿฿',
        'imagePath': 'assets/images/illuzion_club.jpg',
        'tags': ['Club', 'Music'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'thalang_national_museum',
        'name': 'Thalang National Museum',
        'location': 'Thalang, Phuket',
        'category': 'Heritage',
        'rating': 4.3,
        'description': "Explore Phuket's history including the famous Battle of Thalang.",
        'longDescription': '',
        'openHours': '9:00 AM - 4:00 PM',
        'estimatedTime': '1 - 1.5 hours',
        'priceRange': '฿',
        'imagePath': 'assets/images/thalang_national_museum.jpg',
        'tags': ['History', 'Museum'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'promthep_cape',
        'name': 'Promthep Cape',
        'location': 'Rawai, Phuket',
        'category': 'Viewpoint',
        'rating': 4.9,
        'description': 'One of the best sunset viewpoints in Phuket with dramatic coastal scenery.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '45 mins - 1 hour',
        'priceRange': 'Free',
        'imagePath': 'assets/images/promthep_cape.jpg',
        'tags': ['Sunset', 'Viewpoint'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'karon_viewpoint',
        'name': 'Karon Viewpoint',
        'location': 'Karon, Phuket',
        'category': 'Viewpoint',
        'rating': 4.7,
        'description': 'A panoramic viewpoint overlooking Kata Noi, Kata, and Karon beaches.',
        'longDescription': '',
        'openHours': 'Open 24 hours',
        'estimatedTime': '30 - 45 mins',
        'priceRange': 'Free',
        'imagePath': 'assets/images/karon_viewpoint.jpg',
        'tags': ['Viewpoint', 'Scenic'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'phuket_aquarium',
        'name': 'Phuket Aquarium',
        'location': 'Cape Panwa, Phuket',
        'category': 'Attraction',
        'rating': 4.4,
        'description': 'A family-friendly aquarium featuring marine life and educational exhibits.',
        'longDescription': '',
        'openHours': '8:30 AM - 4:30 PM',
        'estimatedTime': '1 - 2 hours',
        'priceRange': '฿฿',
        'imagePath': 'assets/images/phuket_aquarium.jpg',
        'tags': ['Family', 'Indoor'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'jungceylon',
        'name': 'Jungceylon',
        'location': 'Patong, Phuket',
        'category': 'Shopping',
        'rating': 4.3,
        'description': "Patong's largest shopping complex with international brands, cinema, and food court.",
        'longDescription': '',
        'openHours': '11:00 AM - 10:00 PM',
        'estimatedTime': '2 - 3 hours',
        'priceRange': '฿฿',
        'imagePath': 'assets/images/jungceylon.jpg',
        'tags': ['Shopping', 'Indoor'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
      {
        'id': 'central_festival_phuket',
        'name': 'Central Festival Phuket',
        'location': 'Vichitsongkram Rd',
        'category': 'Shopping',
        'rating': 4.5,
        'description': 'A massive lifestyle mall with luxury brands, restaurants, and entertainment.',
        'longDescription': '',
        'openHours': '10:30 AM - 10:00 PM',
        'estimatedTime': '2 - 4 hours',
        'priceRange': '฿฿',
        'imagePath': 'assets/images/central_festival_phuket.jpg',
        'tags': ['Shopping', 'Luxury'],
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
        'createdBy': 'seed',
      },
    ];

    final batch = FirebaseFirestore.instance.batch();
    for (final poi in pois) {
      final id = poi['id'] as String;
      final data = Map<String, dynamic>.from(poi)..remove('id');
      batch.set(col.doc(id), data);
    }
    await batch.commit();
  }
}
