// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7fpFPc4feQsb3MVFqinbrKBYP2hxUpKc',
    appId: '1:22384930715:web:a27bf2c1bfacebca48bb3e',
    messagingSenderId: '22384930715',
    projectId: 'andamove-cc307',
    authDomain: 'andamove-cc307.firebaseapp.com',
    storageBucket: 'andamove-cc307.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfv4i95puxcspTqEiFYGKWp9FdTxCI07g',
    appId: '1:22384930715:android:adf6c1eb3bb75d5648bb3e',
    messagingSenderId: '22384930715',
    projectId: 'andamove-cc307',
    storageBucket: 'andamove-cc307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_DxzrOPmzWulcI-Dvr113JMNkOK1t8A',
    appId: '1:22384930715:ios:21c250cc7a7cd26f48bb3e',
    messagingSenderId: '22384930715',
    projectId: 'andamove-cc307',
    storageBucket: 'andamove-cc307.firebasestorage.app',
    iosBundleId: 'com.example.andamove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc_DxzrOPmzWulcI-Dvr113JMNkOK1t8A',
    appId: '1:22384930715:ios:21c250cc7a7cd26f48bb3e',
    messagingSenderId: '22384930715',
    projectId: 'andamove-cc307',
    storageBucket: 'andamove-cc307.firebasestorage.app',
    iosBundleId: 'com.example.andamove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7fpFPc4feQsb3MVFqinbrKBYP2hxUpKc',
    appId: '1:22384930715:web:b931bf267181288348bb3e',
    messagingSenderId: '22384930715',
    projectId: 'andamove-cc307',
    authDomain: 'andamove-cc307.firebaseapp.com',
    storageBucket: 'andamove-cc307.firebasestorage.app',
  );
}
